sonar.projectKey=jamie-smith-uk_jamie-lifeos
sonar.organization=jamie-smith-uk
sonar.sources=packages
sonar.exclusions=**/node_modules/**,**/dist/**,**/pipeline/**,**/*.test.ts,**/*.tsbuildinfo
sonar.tests=packages
sonar.test.inclusions=**/*.test.ts
